name: Black-Pylint-Pytest

on: [push, pull_request]

jobs:
  black:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--verbose --diff"
          jupyter: true

  lint-test:
    needs: black

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
        timeout 5m
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Analysing the code with pylint ${{ matrix.python-version }}
      run: |
        python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
        tee pylint-${{ matrix.python-version }}.txt

    - name: Upload pylint.txt as artifact ${{ matrix.python-version }}
      uses: actions/upload-artifact@v4
      with:
        name: pylint report ${{ matrix.python-version }}
        path: pylint-${{ matrix.python-version }}.txt
        overwrite: true
        
    - name: Run the test cases ${{ matrix.python-version }}
      run: |
        pytest -v sonetsim/tests/simulator_validator.py